server:
 port: 81
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/cz?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
   username: root
   password: root
mybatis:
 mapper-locations: classpath:mappers/*.xml
